In [1]:
#Import Dependencies 
import pandas as pd
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.utils import to_categorical
from keras.layers import Dense
from keras.utils import to_categorical

/anaconda2/envs/PythonData/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.

In [2]:
#Load dataset 
heart_csv = "Resources/heart.csv"
heart_df = pd.read_csv(heart_csv)
heart_df.head(10)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1
6,56,0,1,140,294,0,0,153,0,1.3,1,0,2,1
7,44,1,1,120,263,0,1,173,0,0.0,2,0,3,1
8,52,1,2,172,199,1,1,162,0,0.5,2,0,3,1
9,57,1,2,150,168,0,1,174,0,1.6,2,0,2,1

In [3]:
outcome = heart_df["sex"]

In [4]:
heart_data = heart_df.drop("sex", axis = 1)
heart_data.head()

,age,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,120,354,0,1,163,1,0.6,2,0,2,1

In [5]:
X = heart_data
y = outcome
print(X.shape, y.shape)

(303, 13) (303,)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y)
X_scaler = StandardScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [7]:
#label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

In [8]:
#encode labels
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [9]:
#Create and add layers to model 
model = Sequential()
model.add(Dense(units=100, activation="relu", input_dim=13))
model.add(Dense(units=100, activation="relu"))
model.add(Dense(units=2, activation = "softmax"))

In [10]:
#Compile Model
model.compile(optimizer="adam",
              loss = "categorical_crossentropy",
              metrics=["accuracy"])

#Fit Model
model.fit(X_train_scaled,
         y_train_categorical,
          epochs= 60,
         shuffle=True,
         verbose=2)

Epoch 1/60
 - 0s - loss: 0.5897 - acc: 0.6696
Epoch 2/60
 - 0s - loss: 0.5359 - acc: 0.6960
Epoch 3/60
 - 0s - loss: 0.5072 - acc: 0.7313
Epoch 4/60
 - 0s - loss: 0.4708 - acc: 0.7797
Epoch 5/60
 - 0s - loss: 0.4496 - acc: 0.8062
Epoch 6/60
 - 0s - loss: 0.4340 - acc: 0.8062
Epoch 7/60
 - 0s - loss: 0.4145 - acc: 0.8150
Epoch 8/60
 - 0s - loss: 0.4001 - acc: 0.8106
Epoch 9/60
 - 0s - loss: 0.3964 - acc: 0.8062
Epoch 10/60
 - 0s - loss: 0.3845 - acc: 0.8150
Epoch 11/60
 - 0s - loss: 0.3606 - acc: 0.8150
Epoch 12/60
 - 0s - loss: 0.3504 - acc: 0.8194
Epoch 13/60
 - 0s - loss: 0.3375 - acc: 0.8282
Epoch 14/60
 - 0s - loss: 0.3268 - acc: 0.8414
Epoch 15/60
 - 0s - loss: 0.3120 - acc: 0.8767
Epoch 16/60
 - 0s - loss: 0.3048 - acc: 0.8767
Epoch 17/60
 - 0s - loss: 0.2971 - acc: 0.8943
Epoch 18/60
 - 0s - loss: 0.2876 - acc: 0.8899
Epoch 19/60
 - 0s - loss: 0.2701 - acc: 0.9031
Epoch 20/60
 - 0s - loss: 0.2610 - acc: 0.8943
Epoch 21/60
 - 0s - loss: 0.2474 - acc: 0.9031
Epoch 22/60
 - 0s - loss: 0.2411 - acc: 0.9075
Epoch 23/60
 - 0s - loss: 0.2372 - acc: 0.9251
Epoch 24/60
 - 0s - loss: 0.2273 - acc: 0.9207
Epoch 25/60
 - 0s - loss: 0.2272 - acc: 0.9207
Epoch 26/60
 - 0s - loss: 0.2265 - acc: 0.9339
Epoch 27/60
 - 0s - loss: 0.2082 - acc: 0.9471
Epoch 28/60
 - 0s - loss: 0.1986 - acc: 0.9471
Epoch 29/60
 - 0s - loss: 0.1918 - acc: 0.9427
Epoch 30/60
 - 0s - loss: 0.1835 - acc: 0.9471
Epoch 31/60
 - 0s - loss: 0.1748 - acc: 0.9515
Epoch 32/60
 - 0s - loss: 0.1767 - acc: 0.9383
Epoch 33/60
 - 0s - loss: 0.1704 - acc: 0.9559
Epoch 34/60
 - 0s - loss: 0.1624 - acc: 0.9604
Epoch 35/60
 - 0s - loss: 0.1585 - acc: 0.9648
Epoch 36/60
 - 0s - loss: 0.1680 - acc: 0.9339
Epoch 37/60
 - 0s - loss: 0.1596 - acc: 0.9427
Epoch 38/60
 - 0s - loss: 0.1478 - acc: 0.9604
Epoch 39/60
 - 0s - loss: 0.1382 - acc: 0.9692
Epoch 40/60
 - 0s - loss: 0.1354 - acc: 0.9692
Epoch 41/60
 - 0s - loss: 0.1303 - acc: 0.9780
Epoch 42/60
 - 0s - loss: 0.1249 - acc: 0.9692
Epoch 43/60
 - 0s - loss: 0.1229 - acc: 0.9736
Epoch 44/60
 - 0s - loss: 0.1199 - acc: 0.9692
Epoch 45/60
 - 0s - loss: 0.1150 - acc: 0.9736
Epoch 46/60
 - 0s - loss: 0.1098 - acc: 0.9736
Epoch 47/60
 - 0s - loss: 0.1063 - acc: 0.9780
Epoch 48/60
 - 0s - loss: 0.1022 - acc: 0.9868
Epoch 49/60
 - 0s - loss: 0.1196 - acc: 0.9648
Epoch 50/60
 - 0s - loss: 0.1115 - acc: 0.9692
Epoch 51/60
 - 0s - loss: 0.1036 - acc: 0.9780
Epoch 52/60
 - 0s - loss: 0.0970 - acc: 0.9868
Epoch 53/60
 - 0s - loss: 0.0918 - acc: 0.9912
Epoch 54/60
 - 0s - loss: 0.0916 - acc: 0.9824
Epoch 55/60
 - 0s - loss: 0.0955 - acc: 0.9780
Epoch 56/60
 - 0s - loss: 0.0882 - acc: 0.9912
Epoch 57/60
 - 0s - loss: 0.0875 - acc: 0.9824
Epoch 58/60
 - 0s - loss: 0.0833 - acc: 0.9868
Epoch 59/60
 - 0s - loss: 0.0834 - acc: 0.9868
Epoch 60/60
 - 0s - loss: 0.0824 - acc: 0.9868

In [28]:
#Score
model_loss, model_accurary = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print( f"Neural Network Score - Loss: {model_loss}, Accuracy: {model_accurary}")

Neural Network Score - Loss: 0.8465511987083837, Accuracy: 0.7368421021260714